### ISSUE TITLE
contents: init: Termux

### ISSUE THREAD

**Issue by Spz2022** [mirrorz-org/mirrorz-help#102]
### 已有镜像链接（Existing Mirrored Repo URL）

https://mirrors.tuna.tsinghua.edu.cn/termux
https://mirrors.bfsu.edu.cn/termux
https://mirrors.ustc.edu.cn/termux
我提供的是一小部分,更多请看 https://github.com/termux/termux-packages/wiki/Mirrors 的 Mirrors hosted in China部分

**Comment by ZenithalHourlyRate** [comment]
@Spz2022 https://help.mirrors.cernet.edu.cn/termux/

**Comment by taoky** [comment]
现在的 https://mirrors.help/termux/ 有什么问题吗？

**Comment by Spz2022** [comment]
忘记看了

**Comment by Spz2022** [comment]
不过把所有 repos 都放 $PREFIX/etc/apt/sources.list 不是明智的选择

**Comment by ZenithalHourlyRate** [comment]
@Spz2022 可以发送PR修改相关内容
