### ISSUE TITLE
kubernetes镜像使用帮助gpg key报错

### ISSUE THREAD

**Issue by Daydreamer-zz** [mirrorz-org/mirrorz-help#112]
### 帮助页面的链接（Help page URL）

https://help.mirrors.cernet.edu.cn/kubernetes/

### 原文 (Text)

首先导入 gpg key：
```bash
sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
```

### 反馈和修正 (Feedback)

在执行`apt update`后如下报错
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05

参考 https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585

应该将地址apt-key.gpg修改为https://dl.k8s.io/apt/doc/apt-key.gpg

sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://dl.k8s.io/apt/doc/apt-key.gpg

**Comment by taoky** [comment]
有兴趣交个 PR 吗？
