### ISSUE TITLE
contents: 南方科技大学PyPI镜像地址不正确

### ISSUE THREAD

**Issue by 66Leo66** [mirrorz-org/mirrorz-help#131]
### 帮助页面的链接（Help page URL）

https://help.mirrors.cernet.edu.cn/pypi/

手动指定 `SUSTech CRA - 南方科技大学开源软件镜像站`

### 原文 (Text)

`https://mirrors.sustech.edu.cn/pypi/web/simple` (https://mirrors.sustech.edu.cn/pypi/web/simple) -> `404`

### 反馈和修正 (Feedback)

`https://mirrors.sustech.edu.cn/pypi/simple` (https://mirrors.sustech.edu.cn/pypi/simple)

```diff
- https://mirrors.sustech.edu.cn/pypi/web/simple
+ https://mirrors.sustech.edu.cn/pypi/simple
```

### 备注 (Note)

见 [PyPI Mirror | SUSTech Open Source Mirrors](https://mirrors.sustech.edu.cn/help/pypi.html#introduction)，该镜像站 PyPI base URL 不带`/web`

目前的错误URL会导致手动指定该镜像站时网页显示的设置命令包含的URL无效，尚不知道是否影响智能选择的302跳转

**Comment by taoky** [comment]
- `/web` 是 https://github.com/mirrorz-org/mirrorz-help/blob/master/contents/pypi.mdx 里面写死的，并且目前没有针对单独镜像站修改内容的设计；
- 302 跳转应该无影响，因为跳转程序不关心 mirrors.example.com/repo/ 后面的东西。

**Comment by sparkcyf** [comment]
我们已经修正了url的问题，并更新了sustech自己的help（https://github.com/SUSTech-CRA/ccse-mirrors-web/commit/3aea97195b58a8d2738007cc117f08f11d1cd248 ），现在 `https://mirrors.sustech.edu.cn/pypi/web/simple` 和 `https://mirrors.sustech.edu.cn/pypi/simple` 都是可用的，但未来我们会逐步放弃使用`https://mirrors.sustech.edu.cn/pypi/simple`作为pypi index，只使用`/pypi/web/simple`以保证和其他镜像站一致。

**Comment by TechCiel** [comment]
@sparkcyf 虽然，但是，其实，直接暴露 simple 才是和官方源对齐的正确做法，web 目录外的东西都是用户不需要的同步状态文件，应该大家都改成用 web 目录作为根。

未来下一版本的 mirrorz 数据规范可能要考虑支持更灵活的 URL 设置。

**Comment by taoky** [comment]
> 未来下一版本的 mirrorz 数据规范可能要考虑支持更灵活的 URL 设置。

现在的帮助设计对一些需要特殊配置的镜像站确实是不太友好的，不止是 pypi 这个问题。
