### ISSUE TITLE
bug: homebrew-bottles重定向问题

### ISSUE THREAD

**Issue by fangzhengjin** [mirrorz-org/mirrorz-help#132]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/mirrorz-org/mirrorz-help/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/mirrorz-org/mirrorz-help/issues).

### 发生了什么（What happened）

从`https://mirrors.cernet.edu.cn/homebrew-bottles`下载文件时, 会被重定向到 `https://homebrew.bintray.com/llvm-17.0.5.sonoma.bottle.tar.gz`, 该服务返回403以及无效的SSL证书, 导致下载无法进行

以此地址为例: https://mirrors.cernet.edu.cn/homebrew-bottles/llvm-17.0.5.sonoma.bottle.tar.gz
经过查看请求日志, 发现被重定向到 `https://mirror.sjtu.edu.cn/homebrew-bottles/llvm-17.0.5.sonoma.bottle.tar.gz` 后, 由该地址再次重定向至 `homebrew.bintray.com`, 如果该站点不再提供`homebrew-bottles`镜像, 是否应该将该站点的重定向移除?

### 期望的现象（What you expected to happen）

同上

### 如何重现此问题（How to reproduce it）

同上

**Comment by taoky** [comment]
> 如果该站点不再提供`homebrew-bottles`镜像, 是否应该将该站点的重定向移除?

相关的设置需要 SJTUG 的同学处理，除非很长时间无法联系到对应负责人，否则 mirrorz-302 不会主动移除到某个镜像站的跳转。

cc @PhotonQuantum

**Comment by PhotonQuantum** [comment]
我站 homebrew-bottles 仓库的正确前缀是 `https://mirror.sjtu.edu.cn/homebrew-bottles/bottles`，该文件的正确路径为 `https://mirror.sjtu.edu.cn/homebrew-bottles/bottles/llvm-17.0.5.sonoma.bottle.tar.gz`，可能需要 mirrorz-302 进行修正

**Comment by taoky** [comment]
Fixed by https://github.com/sjtug/mirror-docker-unified/pull/443.
