### ISSUE TITLE
help页面 ubuntu/ubuntu-ports 没有提供23.10快捷配置

### ISSUE THREAD

**Issue by RevySR** [mirrorz-org/mirrorz-help#135]
https://help.mirrorz.org/ubuntu-ports/
https://help.mirrorz.org/ubuntu/

**Comment by taoky** [comment]
说到这个，每九个月更新一次还是有点麻烦……如果之后发现有类似的问题可以参照 https://github.com/mirrorz-org/mirrorz-help/commit/015e0befe89285480ea377e2a16e676f1da23c41 交个 PR。
