### ISSUE TITLE
contents: QLUT已经移除了OpenWrt镜像

### ISSUE THREAD

**Issue by Mosney** [mirrorz-org/mirrorz-help#150]
### 帮助页面的链接（Help page URL）

https://help.mirrors.cernet.edu.cn/openwrt/

### 手工替换

登录到路由器，并编辑 `/etc/opkg/distfeeds.conf` 文件，将其中的 `http://downloads.openwrt.org` 替换为

<CodeBlock>

```

https://mirrors.qlu.edu.cn/openwrt

```

</CodeBlock>

即可。

### 自动替换

执行如下命令自动替换

<CodeBlock>

```sh

sed -i 's_https\?://downloads.openwrt.org_https://mirrors.qlu.edu.cn/openwrt_' /etc/opkg/distfeeds.conf

```

</CodeBlock>

即可。

### 反馈和修正 (Feedback)

移除OpenWrt下QLUT的选项。  
如果有时间话还可以排查一下是否有其他镜像同样被QLUT无预警/公告删除。

**Comment by taoky** [comment]
信息未更新的原因为 parser <https://github.com/mirrorz-org/mirrorz-parser/blob/master/qlut.js> 中 https://mirrors.qlu.edu.cn/static/status/disk.json 文件不存在，导致 parser 出错，因此 help 使用的 legacy-pack 信息停留在两周前的状态。

QLUT 已经重新添加了这个文件，重新生成后看起来问题已经修复。
