### ISSUE TITLE
feat: update freexian debian elts for Debian 10 Buster

### ISSUE THREAD

**Issue by Oaklight** [mirrorz-org/mirrorz-help#152]
### 特性描述 (Feature Description)

Debian 10 Buster is now available on Freexian. Please update and start to sync the dists. Thanks!

**Comment by taoky** [comment]
> Please update and start to sync the dists.

同步计划由镜像站自行决定。

https://mirrorz.org/list/debian-elts

观察到仅有 TUNA 同步了 debian-elts，并且目前仍在同步，因此 help 会在同步完成之后再做更新。

**Comment by taoky** [comment]
Fixed in https://github.com/mirrorz-org/mirrorz-help/commit/9a48215d5333e86191a8912dc8696ee72b6c3ab7.
