### ISSUE TITLE
feat: Docker 自动安装脚本

### ISSUE THREAD

**Issue by cololi** [mirrorz-org/mirrorz-help#156]
### 特性描述 (Feature Description)

基于 `docker.com` 域名在国内基本无法访问的情况，能否在Docker安装页面替换掉`get.docker.com`的下载链接 用于加速
[页面位置](https://help.mirrors.cernet.edu.cn/docker-ce/#%E8%87%AA%E5%8A%A8%E5%AE%89%E8%A3%85)
脚本
```bash
# 如您使用 curl
curl -fsSL https://get.docker.com/ | sudo -E sh
# 如您使用 wget
wget -O- https://get.docker.com/ | sudo -E sh
```

**Comment by taoky** [comment]
> 能否在Docker安装页面替换掉get.docker.com的下载链接

据我所知目前无镜像站同步了 https://get.docker.com/ 的内容。

**Comment by cololi** [comment]
替换成 `https://raw.githubusercontent.com/docker/docker-install/master/install.sh` 如何？如果可以的话可以加上类似[gh-proxy](https://ghproxy.com/) 的加速推荐

**Comment by taoky** [comment]
> 替换成 `https://raw.githubusercontent.com/docker/docker-install/master/install.sh` 如何？

应该可以，我也咨询了 @Harry-Chen 的意见。

> 如果可以的话可以加上类似[gh-proxy](https://ghproxy.com/) 的加速推荐

原则上帮助文档不包含此类第三方服务。
