### ISSUE TITLE
bug: mozilla 帮助页面的链接有 typo

### ISSUE THREAD

**Issue by RalXYZ** [mirrorz-org/mirrorz-help#163]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/mirrorz-org/mirrorz-help/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/mirrorz-org/mirrorz-help/issues).

### 发生了什么（What happened）

点击 [Mozilla 软件仓库镜像使用帮助页面页面](https://help.mirrorz.org/mozilla/) 的 [在 GitHub 上查看此页的源代码](https://github.com/mirrorz-org/mirrorz-help/blob/master/contents/Mozilla.mdx) 超链接，跳转到的网页显示 404

### 期望的现象（What you expected to happen）

经查，是 url 路径中的 `Mozilla.mdx` 应为 `mozilla.mdx`，如此改动后行为即符合预期

### 如何重现此问题（How to reproduce it）

前文已提及

### 其他需要说明的事项（Anything else we need to know）

建确认是否有其他类似问题，统一进行修改，谢谢

**Comment by taoky** [comment]
检查确认只有 Mozilla 的文件名有问题，已修复。
