### ISSUE TITLE
contents: fedora的帮助内容需要修改

### ISSUE THREAD

**Issue by happy-game** [mirrorz-org/mirrorz-help#175]
### 帮助页面的链接（Help page URL）

https://help.mirrorz.org/fedora/

### 命令替换

用以下命令替换 `/etc/yum.repos.d` 下的文件

<CodeBlock>
```bash
{{sudo}}sed -e 's|^metalink=|#metalink=|g' \
         -e 's|^#baseurl=http://download.example/pub/fedora/linux|baseurl={{http_protocol}}{{mirror}}|g' \
         -i.bak \
         /etc/yum.repos.d/fedora.repo \
         /etc/yum.repos.d/fedora-modular.repo \
         /etc/yum.repos.d/fedora-updates.repo \
         /etc/yum.repos.d/fedora-updates-modular.repo
```

### 反馈和修正 (Feedback)

在fedora39以上不再使用/etc/yum.repos.d/fedora-modular.repo和/etc/yum.repos.d/fedora-update-modular.repo了，但是换源帮助中并没有作出修改，感觉可以像[ustc](https://mirrors.ustc.edu.cn/help/fedora.html)一样分为39以上和39以下.

**Comment by happy-game** [comment]
我可以修改这一部分内容，请问本项目是否有贡献指南，我在[网站](https://help.mirrorz.org/)上点击贡献指南都是跳转到当前页面.

**Comment by taoky** [comment]
> 我可以修改这一部分内容，请问本项目是否有贡献指南，我在[本项目的网站](https://help.mirrorz.org/)上点击贡献指南都是跳转到当前页面.

修改 `contents/fedora.mdx` 的内容即可（建议不要直接在 GitHub Web 上修改，而是本地构建测试以确认无误）。

另外本仓库有 autocorrect CI（会检测诸如中英文之间是否有空格等问题）。
