### ISSUE TITLE
bug: 未能同步所有数据库（软件仓库没有配置服务器信息）

### ISSUE THREAD

**Issue by jielido2023** [mirrorz-org/mirrorz-help#180]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/mirrorz-org/mirrorz-help/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/mirrorz-org/mirrorz-help/issues).

### 发生了什么（What happened）

从TMOE TOOL里更换软件源时直接提示未能同步所有数据库（软件仓库没有配置服务器信息），同时，我已按照配置
![Screenshot_20241216_234924](https://github.com/user-attachments/assets/c1af856c-fbca-45dc-90da-e5e04b1cc319)

### 期望的现象（What you expected to happen）

希望给出个解决办法

### 如何重现此问题（How to reproduce it）

给出个解决办法

### 操作系统（OS Version）

Arch Linux ARM

**Comment by taoky** [comment]
`archlinux` 和 `archlinuxarm` 是两个不同的仓库，不能混用。

![image](https://github.com/user-attachments/assets/a2c073ab-21d8-4175-b751-e44f7f616232)

从你的截图可以看出，设置为 archlinuxarm 时同步是正常的。错误是在使用了 `tmoe` 之后发生的。我不了解相关情况，请考虑向 "tmoe" 的开发者反馈此问题。
