### ISSUE TITLE
Wrong pypi url in PKU mirror

### ISSUE THREAD

**Issue by issaccv** [mirrorz-org/mirrorz-help#26]
The PKU pypi address provided by https://help.mirrorz.org/pypi/ is https://mirrors.pku.edu.cn/pypi/web/simple

However, the correct url in the help of PKU mirror is https://mirrors.pku.edu.cn/pypi/simple

After my test, only the latter address can be used normally

**Comment by ZenithalHourlyRate** [comment]
PKU added /web/simple endpoint now.
