### ISSUE TITLE
debian security源地址仍然写的原来的地址

### ISSUE THREAD

**Issue by fz0000** [mirrorz-org/mirrorz-help#74]
https://github.com/mirrorz-org/mirrorz-help/blob/736292e1dcc59cfa6d119e9168eb2c3ad42811b2/contents/debian.mdx?plain=1#L63-L64
这个地方`security.debian.org/debian-security`是不是忘了换成`{{mirror}}-security`

**Comment by ZenithalHourlyRate** [comment]
您好，您可以参考文档下方的说明

> 不过，一般来说，为了更及时地获得安全更新，不推荐使用镜像站安全更新软件源，因为镜像站往往有同步延迟。参考 https://www.debian.org/security/faq.en.html#mirror
> 
> The purpose of security.debian.org is to make security updates available as quickly and easily as possible.
> 
> Encouraging the use of unofficial mirrors would add extra complexity that is usually not needed and that can cause frustration if these mirrors are not kept up to date.

我们提供了开关选择是否使用官方安全更新源；由于上游并不推荐使用镜像源，选择使用镜像站不能是默认值

**Comment by fz0000** [comment]
Thanks.
