### ISSUE TITLE
contents(Manjaro): 默认的 stable branch 只显示 sjtu 镜像源

### ISSUE THREAD

**Issue by Sciroccogti** [mirrorz-org/mirrorz-help#91]
### 帮助页面的链接（Help page URL）

https://mirror.nju.edu.cn/manjaro/

### 原文 (Text)

生成可用中国镜像站列表：
```
sudo pacman-mirrors -i -c China -m rank
```

### 反馈和修正 (Feedback)

生成可用中国镜像站列表：
```
sudo pacman-mirrors -i -c China -m rank -a --set-branch unstable
```

### 备注 (Note)

branch 只允许 stable 的话，目前只有 sjtu 支持，不过最好的解决方法似乎应当是等待其他源也支持 stable？

**Comment by ZenithalHourlyRate** [comment]
https://repo.manjaro.org/

![Screenshot2023-05-05-23:05:23](https://user-images.githubusercontent.com/19512674/236496022-bd716675-03f7-4824-8084-c92b2b3e3800.png)


这个列表的生成与镜像站的同步状态有关，只能生成 sjtu 似乎是因为其他的镜像站都 out of date，与 stable 还是 unstable 无关

**Comment by Sciroccogti** [comment]
但是我允许 unstable 以后就有其他镜像源了，是因为unstable就会允许out of date 的镜像站吗？感觉不是这样



---- 回复的原邮件 ----
| 发件人 | Hongren (Zenithal) ***@***.***> |
| 日期 | 2023年05月05日 23:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mirrorz-org/mirrorz-help] contents(Manjaro): 默认的 stable branch 只显示 sjtu 镜像源 (Issue #91) |

https://repo.manjaro.org/

这个列表的生成与镜像站的同步状态有关，只能生成 sjtu 似乎是因为其他的镜像站都 out of date，与 stable 还是 unstable 无关

**Comment by ZenithalHourlyRate** [comment]
我个人并未使用过 pacman-mirrors，我的信息都是从 wiki 中来的

https://wiki.manjaro.org/index.php/Pacman-mirrors

> pacman-mirrors will selfupdate by downloading mirrors.json and status.json from repo.manjaro.org 

> Syncronization status
> 
> Pacman-mirrors downloads pool status for the default mirror pool. When you want to regenerate your mirrorlist, your custom pool is updated with the info from the downloaded pool status.
> 
> This ensures you will always use up-to-date mirrors.

**Comment by Sciroccogti** [comment]
已经不再发生。
