### ISSUE TITLE
feat: 一键换源脚本

### ISSUE THREAD

**Issue by SuperManito** [mirrorz-org/mirrorz-help#92]
### 特性描述 (Feature Description)

[**LinuxMirrors**](https://github.com/SuperManito/LinuxMirrors) 是我的项目，可以通过使用 `bash shell` 脚本实现一键换源，这是一个非盈利的开源项目，我想推广给更多的人，不知道贵组织是否感兴趣

**Comment by ZenithalHourlyRate** [comment]
您好，mirrorz 有想法基于 mirrorz.json 提供镜像站数据（正如您提到，"软件源分支命名不符合脚本默认规则，但可以通过命令参数来使用，关于针对各操作系统所默认使用的镜像站分支名称详见此处"，这是这个 json 能解决的问题），基于 mirrorz-help 提供命令和配置文件（以保证文档与实际命令等价），以提供换源脚本，不过该计划暂无时间线。如果您有意愿，我们可以讨论如何结合您的工作与我们的工作。

**Comment by SuperManito** [comment]
> 您好，mirrorz 有想法基于 mirrorz.json 提供镜像站数据（正如您提到，"软件源分支命名不符合脚本默认规则，但可以通过命令参数来使用，关于针对各操作系统所默认使用的镜像站分支名称详见此处"，这是这个 json 能解决的问题），基于 mirrorz-help 提供命令和配置文件（以保证文档与实际命令等价），以提供换源脚本，不过该计划暂无时间线。如果您有意愿，我们可以讨论如何结合您的工作与我们的工作。

可以的，我会一些 Vue 3 和一点点的 React

**Comment by ZenithalHourlyRate** [comment]
> 可以的，我会一些 Vue 3 和一点点的 React

这个事情其实和前端技术栈关系不大，重点还是如何用 bash 处理 mirrorz 的这些数据

您可以参考 mirrorz.json 的[定义](https://github.com/mirrorz-org/mirrorz/#data-format-v17)和[样例](https://github.com/mirrorz-org/mirrorz-json-legacy/blob/master/data/ustc.json)和一种[使用方式](https://github.com/mirrorz-org/oh-my-mirrorz)，以及 mirrorz help 中的配置文件模板和命令（mdx, e.g. [Debian](https://raw.githubusercontent.com/mirrorz-org/mirrorz-help/master/contents/debian.mdx)），这样可以讨论如何与 bash 结合起来

**Comment by ZenithalHourlyRate** [comment]
或者您可以尝试做一种 codegen，即通过解析 json 与 mdx，生成相应 bash 脚本，这样能避免在 shell 中处理 json 与 mdx，同时保证 bash 脚本中使用的命令和配置是最新的

mirrorz-help 本身的维护精力已经较大，样例就是 debian 最近移除了 jessie 与 stretch，这个在我们的帮助中移除了，但未在您的脚本中移除，如果要整合进来，我们不仅需要维护 mdx，也需要维护 shell script，我们认为只维护 mdx 然后将换源配置生成脚本的方式比较可维护

**Comment by SuperManito** [comment]
> > 可以的，我会一些 Vue 3 和一点点的 React
> 
> 这个事情其实和前端技术栈关系不大，重点还是如何用 bash 处理 mirrorz 的这些数据
> 
> 您可以参考 mirrorz.json 的[定义](https://github.com/mirrorz-org/mirrorz/#data-format-v17)和[样例](https://github.com/mirrorz-org/mirrorz-json-legacy/blob/master/data/ustc.json)和一种[使用方式](https://github.com/mirrorz-org/oh-my-mirrorz)，以及 mirrorz help 中的配置文件模板和命令（mdx, e.g. [Debian](https://raw.githubusercontent.com/mirrorz-org/mirrorz-help/master/contents/debian.mdx)），这样可以讨论如何与 bash 结合起来

我认为贵站结合我脚本在调用数据后直接使用我脚本功能的命令选项比较好，当然也可以再单独定制一份脚本，为了良好的兼容性在 bash shell 脚本中应该尽量避免使用很多高级指令，即使我对jq指令很熟悉，但客户端环境不一定会安装curl、wget、jq等软件包，这是不现实的

**Comment by ZenithalHourlyRate** [comment]
> 但客户端环境不一定会安装curl、wget、jq等软件包，这是不现实的

是的，这就是在 https://github.com/mirrorz-org/mirrorz-help/issues/92#issuecomment-1537181810 提出的解决方案。一个最近的可实现的特性就是通过 mirrorz.json 生成一个镜像站到软件源命名规则的映射，并将其嵌入到您的 shell script 中，解决"软件源分支命名不符合脚本默认规则"这个问题

更远的，可以将 mdx 中的配置文件嵌入到您的 shell script 中，每次 mirrorz-help 有改动自动生成相关部分

**Comment by SuperManito** [comment]
> 

我不明白为什么要嵌入到脚本内容中，不知道您是否有注意到我脚本其中的一项功能 [命令选项](https://linuxmirrors.cn/use/command-options)，可以直接自定义使用而不是从默认提供的软件源列表中选择

**Comment by SuperManito** [comment]
> > 但客户端环境不一定会安装curl、wget、jq等软件包，这是不现实的
> 
> 是的，这就是在 [#92 (comment)](https://github.com/mirrorz-org/mirrorz-help/issues/92#issuecomment-1537181810) 提出的解决方案。一个最近的可实现的特性就是通过 mirrorz.json 生成一个镜像站到软件源命名规则的映射，并将其嵌入到您的 shell script 中，解决"软件源分支命名不符合脚本默认规则"这个问题
> 
> 更远的，可以将 mdx 中的配置文件嵌入到您的 shell script 中，每次 mirrorz-help 有改动自动生成相关部分

我不明白为什么要嵌入到脚本内容中，不知道您是否有注意到我脚本其中的一项功能 [命令选项](https://linuxmirrors.cn/use/command-options)，可以直接自定义使用而不是从默认提供的软件源列表中选择

**Comment by ZenithalHourlyRate** [comment]
> 我想推广给更多的人，不知道贵组织是否感兴趣

您期待怎样的形式，不同的形式意味着不同的技术选择

**Comment by SuperManito** [comment]
> > 我想推广给更多的人，不知道贵组织是否感兴趣
> 
> 您期待怎样的形式，不同的形式意味着不同的技术选择

我想象中的是你们再提供一份关于镜像分支的json数据，然后在md中展示一键脚本命令

```
bash <(curl -sSL https://linuxmirrors.cn/main.sh) \
  --source {{source}} \
  --branch {{branch}}
```

这样就可以使用了，我不清楚你们想如何利用我的脚本，我可以单独定制一份，但是在脚本内内嵌各个镜像站的数据这并不现实

**Comment by ZenithalHourlyRate** [comment]
> 在md中展示一键脚本命令

这里其实也有两个方面

> > 不同的形式意味着不同的技术选择

一个是在 mirrors.help （海外）上展示，这个会相对宽松一些，我们可以提供单独一节说明可以使用第三方软件一键换源，并依靠我们的数据给出样例命令，但同时也会说明 mirrorz 不对此做出任何保障

另一个是在 help.mirrors.cernet.edu.cn 以及各个镜像站的帮助文档中展示，这个由于 .edu.cn 的关系，会要求相应脚本与 mirrorz 强相关，经过讨论（目前内部关于换源软件有很多讨论，尚无定论）大家认同该方案，定制的脚本的 repo 在 mirrorz-org 内, 且直接或间接使用了 mirrorz.json 与 mirrorz-help 生成数据和配置，最终脚本会通过 help.mirrors.cernet.edu.cn 分发

**Comment by SuperManito** [comment]
> > 在md中展示一键脚本命令
> 
> 这里其实也有两个方面
> 
> > > 不同的形式意味着不同的技术选择
> 
> 一个是在 mirrors.help （海外）上展示，这个会相对宽松一些，我们可以提供单独一节说明可以使用第三方软件一键换源，并依靠我们的数据给出样例命令，但同时也会说明 mirrorz 不对此做出任何保障
> 
> 另一个是在 help.mirrors.cernet.edu.cn 以及各个镜像站的帮助文档中展示，这个由于 .edu.cn 的关系，会要求相应脚本与 mirrorz 强相关，经过讨论（目前内部关于换源软件有很多讨论，尚无定论）大家认同该方案，定制的脚本的 repo 在 mirrorz-org 内, 且直接或间接使用了 mirrorz.json 与 mirrorz-help 生成数据和配置，最终脚本会通过 help.mirrors.cernet.edu.cn 分发

理解了，看你们想怎么弄了，反正我脚本既然支持命令选项那就意味着可以在脚本内定义变量来使用，可以直接插入定义变量的代码到脚本文件中例如在脚本头部或底部，你们提要求我来定制就行了

**Comment by ZenithalHourlyRate** [comment]
> 理解了，看你们想怎么弄了

我自然是希望是后者，因为这在路线图中。不过具体技术方案大家是否接受，还需要大家的意见，因为这意味着成为官方项目。我建议的路径是这样：先在您的个人账户下做，做出来一版以后大家反馈迭代几轮，最终大家觉得应该有的都有了，再迁移到 mirrorz-org 中并与其他项目（e.g. mirrorz-help 展示）整合

我个人的反馈在于脚本要与 mirrorz 强相关，即使用 mirrorz 的资源，且维护成本低，一方面是要与 mirrorz-help 保持一致，另一方面是较长的 shell script 难以维护，我更偏向于通过 codegen 的方式通过小模块生成最终脚本;另一点在于 mirrorz-org 内的脚本不做非 mirrorz 站点的换源，例如阿里云

其他同学例如 @RalXYZ 也有一些其他意见，例如使用前告知风险与明确使用者的责任，展示危险命令与改动等

**Comment by SuperManito** [comment]
> > 理解了，看你们想怎么弄了
> 
> 
> 
> 我自然是希望是后者，因为这在路线图中。不过具体技术方案大家是否接受，还需要大家的意见，因为这意味着成为官方项目。我建议的路径是这样：先在您的个人账户下做，做出来一版以后大家反馈迭代几轮，最终大家觉得应该有的都有了，再迁移到 mirrorz-org 中并与其他项目（e.g. mirrorz-help 展示）整合
> 
> 
> 
> 我个人的反馈在于脚本要与 mirrorz 强相关，即使用 mirrorz 的资源，且维护成本低，一方面是要与 mirrorz-help 保持一致，另一方面是较长的 shell script 难以维护，我更偏向于通过 codegen 的方式通过小模块生成最终脚本;另一点在于 mirrorz-org 内的脚本不做非 mirrorz 站点的换源，例如阿里云
> 
> 
> 
> 其他同学例如 @RalXYZ 也有一些其他意见，例如使用前告知风险与明确使用者的责任，展示危险命令与改动等
> 
> 

首先关于脚本内容长度，其70%的内容来自repo源文件源码，由于脚本要适配众多环境例如客户端repo源文件丢失，所以脚本的流程是先备份然后删除并重新生成，在有更好的解决方案之前这是最佳的，所以即使针对一个系统定制那么代码普遍越会超过千行
我不太了解codegen，我的脚本是针对多个系统适配的集合脚本而不是针对某一个系统，里面有大量的判断逻辑，通过其它语言的代码去模块儿化生成是不现实的，那样的话反而工作量会更大
如果针对单一系统定制shell脚本那我认为与直接用sed命令替换没有什么区别，我的脚本可以在没有软件源的情况下创建，而md教程中的替换命令是建立在原有官方软件源的情况下替换，这是很大的区别
我会在明天提供一个定制的精简版，你们可以先看看效果

**Comment by SuperManito** [comment]
> > 理解了，看你们想怎么弄了
> 
> 
> 
> 我自然是希望是后者，因为这在路线图中。不过具体技术方案大家是否接受，还需要大家的意见，因为这意味着成为官方项目。我建议的路径是这样：先在您的个人账户下做，做出来一版以后大家反馈迭代几轮，最终大家觉得应该有的都有了，再迁移到 mirrorz-org 中并与其他项目（e.g. mirrorz-help 展示）整合
> 
> 
> 
> 我个人的反馈在于脚本要与 mirrorz 强相关，即使用 mirrorz 的资源，且维护成本低，一方面是要与 mirrorz-help 保持一致，另一方面是较长的 shell script 难以维护，我更偏向于通过 codegen 的方式通过小模块生成最终脚本;另一点在于 mirrorz-org 内的脚本不做非 mirrorz 站点的换源，例如阿里云
> 
> 
> 
> 其他同学例如 @RalXYZ 也有一些其他意见，例如使用前告知风险与明确使用者的责任，展示危险命令与改动等
> 
> 

关于告知使用风险我认为是建立在脚本内容不受控制下的，就像你说的在国外站mirror.help加上这种提示是合理的，我想的是我会在我的仓库发布精简版然后由你们来审核，之后怎么分发下去我就不管了，审核过的就没必要告知风险，反而会带来问题，到时候用户出了任何问题都会来怪这个脚本

**Comment by ZenithalHourlyRate** [comment]
@SuperManito 明天出精简版这个事情可以不急，我觉得我们还有很多细节要讨论清楚（明天再讨论了，现在我离开键盘了）才开始写代码，避免浪费工作

告知风险这个事情我的表达可能没太到位，之后会拜托同学给一个更加详细的说明

**Comment by SuperManito** [comment]
> @SuperManito 明天出精简版这个事情可以不急，我觉得我们还有很多细节要讨论清楚（明天再讨论了，现在我离开键盘了）才开始写代码，避免浪费工作
> 
> 告知风险这个事情我的表达可能没太到位，之后会拜托同学给一个更加详细的说明

你们既然是联合运营，那可以先让成员体验体验脚本效果，我的目的肯定是要给我的项目提高曝光度的，不能说帮你们定制弄半天最后成了做公益，按道理来说两份脚本大体内容一致我才好维护，我也没那么多精力

**Comment by SuperManito** [comment]
> @SuperManito 明天出精简版这个事情可以不急，我觉得我们还有很多细节要讨论清楚（明天再讨论了，现在我离开键盘了）才开始写代码，避免浪费工作
> 
> 告知风险这个事情我的表达可能没太到位，之后会拜托同学给一个更加详细的说明

[精简版](https://linuxmirrors.cn/use/#%E4%B8%AD%E5%9B%BD%E6%95%99%E8%82%B2%E7%BD%91%E4%B8%93%E7%94%A8%E5%AE%9E%E9%AA%8C%E6%80%A7)已上线

**Comment by RalXYZ** [comment]
> 告知风险这个事情我的表达可能没太到位，之后会拜托同学给一个更加详细的说明

@SuperManito 
Hi，我们昨天内部简单讨论了一下。
我体验了一下你的脚本，个人感觉你这个项目写的挺好的，很多朋友也是这样认为的😊能看出需要很大的工作量。

我补充一下 @ZenithalHourlyRate 提到的**告知风险**是啥意思。

## 背景

我之前在一个学生组织工作过。这个学生组织面向校内学生，开发了一个能查课表、查考试的 app。由于缓存、网络波动等问题，客户端的信息可能存在更新不实时的问题。这意味着，一旦教务网对考试时间进行临时变动，缓存在学生设备里的信息可能并不会更新，使得学生并不能实时感知到考试时间变动。
我们之前没有特别重视这一问题，仅仅是在考试周开始前向用户推送一条消息，告知用户考试信息以教务网为准。此外，教务处每次发布考试安排时，也都会用红字告知学生不要相信我们开发的第三方 app，要以教务网信息为准。我们以为这不会导致问题。

然而，在某学期，一场考试的时间真的发生了临时的改动。由于数据同步不及时，且有同学忽视了警告信息，完全相信我们的 app，导致几位同学错过了考试时间，因此只能参加补考。这对他们的成绩造成了严重的影响。

此事发生后，我所在的学生组织被学校相关部门约谈，且相关部门大大收紧了对我们的审查。这导致我们的正常开发节奏受到了严重的影响。


## 我想表达什么

以上是我在昨天的内部讨论中举出的一个案例。自从这个事件发生后，我对**自动化工具**的观点变得越来越谨慎。
先前，用户使用镜像站的流程是，用户在前端页面主动选择发行版版本之类的参数，然后手动把配置拷贝、再粘贴到系统的配置文件里。在此链路中，镜像站维护者基本上不需要负责，因为用户的手动操作数太多了，大部分行为都是用户主观的、有感知的行为。即使出现了问题，无论是用户自己还是官方，往往都会把问题归因在用户自身的误操作上。
但，**自动化脚本的用户操作数可能比较低**。自动化脚本会自动检测用户的操作系统环境相关信息，而操作系统的环境又千差万别，可能出现一些检测错误。

一旦用户或官方把问题归因给我们，就会对我们造成影响。特别是，TUNA 的项目不仅仅会在清华的域名上部署，还会在教育网的域名上部署。一旦出现问题，影响面会非常广，无论是对用户还是对开发工作。

## 按照我的理解，应该怎么做
1. 至少脚本里要有一步，明确输出脚本检测出的**当前设备发行版和版本**，并要求用户手动确认。
2. 用户感知还可以做的再强一些，比如**强制用户手动输入一段文字**，比如让用户手动输入确认一遍当前系统的版本之类。这是否有必要，以及以何种形式做，都可以讨论。
3. **明确输出脚本做出的改动**，比如把新老两个配置文件做个 diff 输出出来，并要求用户手动确认。

以上全部内容只是我的个人想法。具体是否执行、如何分工，还需讨论后再做决断。

**Comment by ZenithalHourlyRate** [comment]
> 如果针对单一系统定制shell脚本那我认为与直接用sed命令替换没有什么区别，我的脚本可以在没有软件源的情况下创建，而md教程中的替换命令是建立在原有官方软件源的情况下替换，这是很大的区别

我的意思并不是一键脚本中全部使用为md教程中的 sed 替换命令（相反我个人并不喜欢在一键脚本中使用 sed），而是说将md教程中的配置文件模板搬入一键脚本中，现在两者是单独维护的，这个维护难度较大。

举个例子，一键脚本和md教程中都有 debian sources.list 的模板，但两者内容不一致

https://github.com/SuperManito/LinuxMirrors/blob/2f4f403ca24f3202c6b4fbee5d2bdaeba40ce2ea/ChangeMirrors.sh#L1025-L1045

https://github.com/mirrorz-org/mirrorz-help/blob/543b9ebbc16c7537be1064b4741f262b22203feb/contents/debian.mdx?plain=1#L16-L65

在现在，每当有人改了后者，都需要手动改前者；我们希望在改动后者的同时前者能自动被改动，同时后者的大量选项也能一并导入到一键脚本中，从而保证一致性

对于其他的例如 apt-get/yum 这些命令，也应该从md教程中导出，这样即降低了我们的维护难度，用户也能体验到网页和脚本的一致性

https://github.com/SuperManito/LinuxMirrors/blob/2f4f403ca24f3202c6b4fbee5d2bdaeba40ce2ea/ChangeMirrors.sh#L894-L896

**Comment by SuperManito** [comment]
> > 告知风险这个事情我的表达可能没太到位，之后会拜托同学给一个更加详细的说明
> 
> @SuperManito Hi，我们昨天内部简单讨论了一下。 我体验了一下你的脚本，个人感觉你这个项目写的挺好的，很多朋友也是这样认为的😊能看出需要很大的工作量。
> 
> 我补充一下 @ZenithalHourlyRate 提到的**告知风险**是啥意思。
> 
> ## 背景
> 我之前在一个学生组织工作过。这个学生组织面向校内学生，开发了一个能查课表、查考试的 app。由于缓存、网络波动等问题，客户端的信息可能存在更新不实时的问题。这意味着，一旦教务网对考试时间进行临时变动，缓存在学生设备里的信息可能并不会更新，使得学生并不能实时感知到考试时间变动。 我们之前没有特别重视这一问题，仅仅是在考试周开始前向用户推送一条消息，告知用户考试信息以教务网为准。此外，教务处每次发布考试安排时，也都会用红字告知学生不要相信我们开发的第三方 app，要以教务网信息为准。我们以为这不会导致问题。



> 
> 然而，在某学期，一场考试的时间真的发生了临时的改动。由于数据同步不及时，且有同学忽视了警告信息，完全相信我们的 app，导致几位同学错过了考试时间，因此只能参加补考。这对他们的成绩造成了严重的影响。
> 
> 此事发生后，我所在的学生组织被学校相关部门约谈，且相关部门大大收紧了对我们的审查。这导致我们的正常开发节奏受到了严重的影响。
> 
> ## 我想表达什么
> 以上是我在昨天的内部讨论中举出的一个案例。自从这个事件发生后，我对**自动化工具**的观点变得越来越谨慎。 先前，用户使用镜像站的流程是，用户在前端页面主动选择发行版版本之类的参数，然后手动把配置拷贝、再粘贴到系统的配置文件里。在此链路中，镜像站维护者基本上不需要负责，因为用户的手动操作数太多了，大部分行为都是用户主观的、有感知的行为。即使出现了问题，无论是用户自己还是官方，往往都会把问题归因在用户自身的误操作上。 但，**自动化脚本的用户操作数可能比较低**。自动化脚本会自动检测用户的操作系统环境相关信息，而操作系统的环境又千差万别，可能出现一些检测错误。
> 
> 一旦用户或官方把问题归因给我们，就会对我们造成影响。特别是，TUNA 的项目不仅仅会在清华的域名上部署，还会在教育网的域名上部署。一旦出现问题，影响面会非常广，无论是对用户还是对开发工作。
> 
> ## 按照我的理解，应该怎么做
> 1. 至少脚本里要有一步，明确输出脚本检测出的**当前设备发行版和版本**，并要求用户手动确认。
> 2. 用户感知还可以做的再强一些，比如**强制用户手动输入一段文字**，比如让用户手动输入确认一遍当前系统的版本之类。这是否有必要，以及以何种形式做，都可以讨论。
> 3. **明确输出脚本做出的改动**，比如把新老两个配置文件做个 diff 输出出来，并要求用户手动确认。
> 
> 以上全部内容只是我的个人想法。具体是否执行、如何分工，还需讨论后再做决断。

按照你的需求更新了一些内容，你跑跑看看效果吧

**Comment by SuperManito** [comment]
> > 如果针对单一系统定制shell脚本那我认为与直接用sed命令替换没有什么区别，我的脚本可以在没有软件源的情况下创建，而md教程中的替换命令是建立在原有官方软件源的情况下替换，这是很大的区别
> 
> 我的意思并不是一键脚本中全部使用为md教程中的 sed 替换命令（相反我个人并不喜欢在一键脚本中使用 sed），而是说将md教程中的配置文件模板搬入一键脚本中，现在两者是单独维护的，这个维护难度较大。
> 
> 举个例子，一键脚本和md教程中都有 debian sources.list 的模板，但两者内容不一致
> 
> https://github.com/SuperManito/LinuxMirrors/blob/2f4f403ca24f3202c6b4fbee5d2bdaeba40ce2ea/ChangeMirrors.sh#L1025-L1045
> 
> https://github.com/mirrorz-org/mirrorz-help/blob/543b9ebbc16c7537be1064b4741f262b22203feb/contents/debian.mdx?plain=1#L16-L65
> 
> 在现在，每当有人改了后者，都需要手动改前者；我们希望在改动后者的同时前者能自动被改动，同时后者的大量选项也能一并导入到一键脚本中，从而保证一致性
> 
> 对于其他的例如 apt-get/yum 这些命令，也应该从md教程中导出，这样即降低了我们的维护难度，用户也能体验到网页和脚本的一致性
> 
> https://github.com/SuperManito/LinuxMirrors/blob/2f4f403ca24f3202c6b4fbee5d2bdaeba40ce2ea/ChangeMirrors.sh#L894-L896

按照我的实际，你们在分发的时候直接改头部变量就行了

**Comment by ZenithalHourlyRate** [comment]
> 你们在分发的时候直接改头部变量就行了

比如 debian sid/testing 现在如何支持？这个在 md 中是支持的

比如 non-free-firmware 理论上是 debian 12 以后才加上的，现在我们两家处理方式不一样，您的处理方式可能会导致用户在 apt update 时出现 warning

比如 md 中现在删除了 debian 8 与 9（它们现在被移动到了 debian-archive），这个改动要如何同步到脚本中？

比如 debian 13 Trixie 发布后，除了要修改 md，也要手动修改脚本

https://github.com/SuperManito/LinuxMirrors/blob/a6341710e0f12d9211dc6a07b9f74663e548566a/MirrorZ.sh#L270-L274

手动修改是有较大维护难度的

**Comment by SuperManito** [comment]
> > 如果针对单一系统定制shell脚本那我认为与直接用sed命令替换没有什么区别，我的脚本可以在没有软件源的情况下创建，而md教程中的替换命令是建立在原有官方软件源的情况下替换，这是很大的区别
> 
> 我的意思并不是一键脚本中全部使用为md教程中的 sed 替换命令（相反我个人并不喜欢在一键脚本中使用 sed），而是说将md教程中的配置文件模板搬入一键脚本中，现在两者是单独维护的，这个维护难度较大。
> 
> 举个例子，一键脚本和md教程中都有 debian sources.list 的模板，但两者内容不一致
> 
> https://github.com/SuperManito/LinuxMirrors/blob/2f4f403ca24f3202c6b4fbee5d2bdaeba40ce2ea/ChangeMirrors.sh#L1025-L1045
> 
> https://github.com/mirrorz-org/mirrorz-help/blob/543b9ebbc16c7537be1064b4741f262b22203feb/contents/debian.mdx?plain=1#L16-L65
> 
> 在现在，每当有人改了后者，都需要手动改前者；我们希望在改动后者的同时前者能自动被改动，同时后者的大量选项也能一并导入到一键脚本中，从而保证一致性
> 
> 对于其他的例如 apt-get/yum 这些命令，也应该从md教程中导出，这样即降低了我们的维护难度，用户也能体验到网页和脚本的一致性
> 
> https://github.com/SuperManito/LinuxMirrors/blob/2f4f403ca24f3202c6b4fbee5d2bdaeba40ce2ea/ChangeMirrors.sh#L894-L896

你讲的一致性是建立在 Debian 派系 Linux 上的，其它派系例如红帽就不存在这种问题，你也管不了原始repo源文件的内容，保证脚本实现的功能一致就行了，而且你们那个debian-security官方源注释对于我们用脚本的用户来说毫无意义，一旦用了脚本就会养成依赖性，不要把简单的东西搞复杂，用脚本的初衷就是为了省事

**Comment by ZenithalHourlyRate** [comment]
> 而且你们那个debian-security官方源注释对于我们用脚本的用户来说毫无意义

注释只是因为我们模板语言的语法限制，而且我也知道大家肯定会换用镜像站 security 源，实际上这个存在上为了我们履行告知义务，因为大家都不是 debian-security 的官方镜像，一旦用户因为安全更新不及时而造成损失，这个是用户的选择，而不应该怪罪镜像站

**Comment by SuperManito** [comment]
> non-free-firmware

像 Debian testing 这种不在我脚本适配范围内的操作系统或版本就不是我需要解决的问题，这应该是你们需要解决的问题，在合适的页面进行展示，当然后期我脚本会不断完善对更多操作系统和版本的支持，这取决于我的经验和是否有一定的用户群体，你不能把我的脚本设计成百科全书什么都支持
关于 Debian 12 `non-free-firmware` 的适配方法我参考的就是贵站的md文档

关于 debian 8 和 9，你不说我都不知道，我一会儿适配一下就行了，这种版本兼容问题你们经验肯定比我丰富，一起完善就行了

我的脚本新加了版本验证，不在支持范围内的版本会退出，之前只是验证了`派系`，所以在我的官网文档中写到 `不在此支持范围内的系统不要允许脚本`，现在不存在这个问题了

**Comment by ZenithalHourlyRate** [comment]
> 关于 debian 8 和 9，你不说我都不知道，我一会儿适配一下就行了，这种版本兼容问题你们经验肯定比我丰富，一起完善就行了

这就是维护难度，而且长期来说并不是一句一起完善就能解决的事情，而是有大量的工作量。我建议还是有一种自动同步的机制。

> 这应该是你们需要解决的问题

我提出的从md导入就是在解决这个问题

**Comment by SuperManito** [comment]
> > 而且你们那个debian-security官方源注释对于我们用脚本的用户来说毫无意义
> 
> 注释只是因为我们模板语言的语法限制，而且我也知道大家肯定会换用镜像站 security 源，实际上这个存在上为了我们履行告知义务，因为大家都不是 debian-security 的官方镜像，一旦用户因为安全更新不及时而造成损失，这个是用户的选择，而不应该怪罪镜像站

我认为针对你说的这些问题最好是是设计一个 dropdown，里面针对不同版本号的修改内容，这样就不用在一个页面上写好几个版本的修改方法了，所以我认为这是你们网站的结构问题

**Comment by SuperManito** [comment]
> > 关于 debian 8 和 9，你不说我都不知道，我一会儿适配一下就行了，这种版本兼容问题你们经验肯定比我丰富，一起完善就行了
> 
> 这就是维护难度，而且长期来说并不是一句一起完善就能解决的事情，而是有大量的工作量。我建议还是有一种自动同步的机制。
> 
> > 这应该是你们需要解决的问题
> 
> 我提出的从md导入就是在解决这个问题

我觉得维护一个脚本比维护很多个脚本要轻松

> > 关于 debian 8 和 9，你不说我都不知道，我一会儿适配一下就行了，这种版本兼容问题你们经验肯定比我丰富，一起完善就行了
> 
> 这就是维护难度，而且长期来说并不是一句一起完善就能解决的事情，而是有大量的工作量。我建议还是有一种自动同步的机制。
> 
> > 这应该是你们需要解决的问题
> 
> 我提出的从md导入就是在解决这个问题

你对于脚本的看法还是有些误解，脚本以实用为主不是百科全书，而且按照你的思路要给很多较为落后的版本去单独适配一个脚本，那做这些工作有什么意义呢，对我来说就没意义，因为根本就没人用，有人用就会提需求

**Comment by ZenithalHourlyRate** [comment]
> 我认为针对你说的这些问题最好是是设计一个 dropdown，里面展示针对不同版本号的修改内容，这样就不用在一个页面上写好几个版本的修改方法了，所以我认为这是你们网站的结构问题

mdx 本身的技术问题也很多，我也不想在这里详细展开，举例来说，这个模板语言不只要在 mirrorz-help 使用，还要接入 tuna 等前端，一个过强的表达会让人难以接入，过弱的表达对大家没用

另一个样例其实是全部展开，例如 [ZJU Debian](https://github.com/ZJUSCT/mirror-front/blob/94ca707ea35ab3cf95011d534e4f4f4a31ccbb49/docs/zh/debian.mdx?plain=1#L17-L60)，而这在我个人看来是无法维护的

**Comment by ZenithalHourlyRate** [comment]
> 脚本以实用为主不是百科全书，而且按照你的思路要给很多较为落后的版本去单独适配一个脚本，那做这些工作有什么意义呢，对我来说就没意义，因为根本就没人用，有人用就会提需求

所以还是回到这句话

> 您期待怎样的形式，不同的形式意味着不同的技术选择

在 mirrorz-org 的名下则需要做到与 mirrorz 已有的项目有一定的一致性，不在名下那则随意

**Comment by SuperManito** [comment]
> > 我认为针对你说的这些问题最好是是设计一个 dropdown，里面展示针对不同版本号的修改内容，这样就不用在一个页面上写好几个版本的修改方法了，所以我认为这是你们网站的结构问题
> 
> mdx 本身的技术问题也很多，我也不想在这里详细展开，举例来说，这个模板语言不只要在 mirrorz-help 使用，还要接入 tuna 等前端，一个过强的表达会让人难以接入，过弱的表达对大家没用
> 
> 另一个样例其实是全部展开，例如 [ZJU Debian](https://github.com/ZJUSCT/mirror-front/blob/94ca707ea35ab3cf95011d534e4f4f4a31ccbb49/docs/zh/debian.mdx?plain=1#L17-L60)，而这在我个人看来是无法维护的

我还是认为脚本只是个工具，不能把它当百科全书用，至于在md中如何展示那不是我要考虑的问题，按照你的设想是去把脚本内容拆分，我没有那么多精力去维护它，而且没有什么意义

我现在已经设计好了一个工作流程，我优先发布到我的仓库内，你们在审核后将脚本搬运到你们的仓库内，然后在分发下去的时候修改脚本内头部定义的变量，还可以根据系统拆分成多个以此针对镜像分支命名不规范的问题

**Comment by ZenithalHourlyRate** [comment]
> 按照你的设想是去把脚本内容拆分，我没有那么多精力去维护它，而且没有什么意义

> 你们在审核后将脚本搬运到你们的仓库内

我提出这个是因为我们搬入进来的话我们也有维护难度，我们也想减小这个

**Comment by ZenithalHourlyRate** [comment]
> 我提出这个是因为我们搬入进来的话我们也有维护难度，我们也想减小这个

这个事情要考虑项目如何可持续发展，比如五年后谁来接手和管理？

> > 关于 debian 8 和 9，你不说我都不知道，我一会儿适配一下就行了，这种版本兼容问题你们经验肯定比我丰富，一起完善就行了

> 这就是维护难度，而且长期来说并不是一句一起完善就能解决的事情，而是有大量的工作量。我建议还是有一种自动同步的机制。

这么多改动谁来一个个应用上去？

> > 我提出的从md导入就是在解决这个问题

> 我觉得维护一个脚本比维护很多个脚本要轻松

从 mdx 导入并不意味着多个脚本，最终可以通过某种方式合并成一个脚本

**Comment by SuperManito** [comment]
> > 我提出这个是因为我们搬入进来的话我们也有维护难度，我们也想减小这个
> 
> 这个事情要考虑项目如何可持续发展，比如五年后谁来接手和管理？
> 
> > > 关于 debian 8 和 9，你不说我都不知道，我一会儿适配一下就行了，这种版本兼容问题你们经验肯定比我丰富，一起完善就行了
> 
> > 这就是维护难度，而且长期来说并不是一句一起完善就能解决的事情，而是有大量的工作量。我建议还是有一种自动同步的机制。
> 
> 这么多改动谁来一个个应用上去？
> 
> > > 我提出的从md导入就是在解决这个问题
> 
> > 我觉得维护一个脚本比维护很多个脚本要轻松
> 
> 从 mdx 导入并不意味着多个脚本，最终可以通过某种方式合并成一个脚本

你要是想弄就看着弄吧，我只能说你们后面如果设计出了一种工作流程我可以帮着看看，如果要大改我脚本的工作逻辑那我无能为力
